apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # The name of the CRD must be in the format <plural>.<group>
  name: vms.infra.example.com
spec:
  # The group name for your API. It's recommended to use a domain you control.
  group: infra.example.com
  # Scope indicates if the custom resource is namespaced or cluster-scoped.
  # VMs are typically namespaced as they belong to a specific tenant/project.
  scope: Namespaced
  names:
    # Plural name to be used in URLs, e.g., /apis/infra.example.com/v1alpha1/vms
    plural: vms
    # Singular name to be used as an alias on the CLI and for display
    singular: vm
    # Kind is the CamelCased singular type name of your custom resource.
    # This will be the `kind` field in the YAML for your custom resource.
    kind: VM
    # Short names can be used as abbreviations on the CLI
    shortNames:
      - vm
  versions:
    - name: v1alpha1 # The version of the API, e.g., v1alpha1, v1beta1, v1
      served: true    # Specifies that this version should be served via the API
      storage: true   # There must be exactly one version marked as `storage: true`
      # Schema for the custom resource's spec and status.
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: Specification for the VM.
              required:
                - diskSize
                - ram
                - users
              properties:
                diskSize:
                  type: integer
                  format: int32
                  description: |
                    Size of the VM's primary disk in GiB (Gigabytes).
                    Must be a positive integer.
                  minimum: 1
                  example: 50
                ram:
                  type: integer
                  format: int32
                  description: |
                    Amount of RAM allocated to the VM in MiB (Megabytes).
                    Must be a positive integer, usually a multiple of 512 or 1024.
                  minimum: 512
                  example: 4096 # 4 GiB
                users:
                  type: array
                  description: |
                    A list of user names to be provisioned on the VM.
                    These users typically have SSH access or are created within the OS.
                  items:
                    type: string
                    minLength: 1 # Usernames shouldn't be empty
#                 uniqueItems: true # Ensure no duplicate usernames
                  x-kubernetes-list-type: set # Treat as a set, order doesn't matter
                  example:
                    - alice
                    - bob
                    - charlie
            # Status subresource (optional but highly recommended for controllers)
            status:
              type: object
              description: Current status of the VM.
              properties:
                provisioningStatus:
                  type: string
                  description: |
                    The current provisioning status of the VM (e.g., Pending, Creating, Running, Failed, Terminating).
                  enum:
                    - Pending
                    - Creating
                    - Running
                    - Stopped
                    - Failed
                    - Terminating
                    - Terminated
                  example: Running
                ipAddress:
                  type: string
                  format: ipv4
                  description: The IP address assigned to the VM once it's running.
                  example: "192.168.1.100"
                lastHeartbeatTime:
                  type: string
                  format: date-time
                  description: The last time the VM reported its status.
                  example: "2023-10-27T10:00:00Z"
      # Additional printer columns allow `kubectl get vm` to show more useful information
      additionalPrinterColumns:
        - name: DiskSize
          type: integer
          jsonPath: .spec.diskSize
          description: VM Disk Size in GiB
        - name: RAM
          type: integer
          jsonPath: .spec.ram
          description: VM RAM in MiB
        - name: Status
          type: string
          jsonPath: .status.provisioningStatus
          description: Current provisioning status of the VM
        - name: IP
          type: string
          jsonPath: .status.ipAddress
          description: IP Address of the VM
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
          description: How long ago the VM was created
